### PR TITLE
Now only uses the node-zabbix-sender module.

### PR DESCRIPTION
**Pull request by steevhise**
Ok, this is ready to merge now, I think. Have addressed all your comments, and simplified things more.  have a look-see... Thanks....

### CODE REVIEW

**Comment by steevhise** [comment]
Any thoughts on this?

**Comment by parkerd** [comment]
Sorry about the delay, I'll take a look this weekend. Thanks again for cleaning it up!

**Comment by parkerd** [comment]
I need to perform some general cleanup on this repo and double check the changes locally. Afterwards I'll publish a new version to npm.

**Comment by steevhise** [comment]
Excellent!

**Pull request merged**
